version: '3.8'

services:
  orderingapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file: .env

  db:
    image: mongo
    ports:
      - 27016:27017
    volumes:
      - orderingapp:/data/db

volumes:
  orderingapp:
